### ISSUE TITLE
compiled wii version?

### ISSUE THREAD

**Issue by ghost** [camthesaxman/cubecraft#1]
could you provide a compiled dol file for wii?

**Comment by ghost** [comment]
I got it to compile and it went to the blue main menu but none of the buttons on the gc controller work so I am stuck at the main menu.

**Comment by camthesaxman** [comment]
You should be able to navigate the menus with the control stick or control pad and A button on the Gamecube controller. Make sure the controller is plugged in correctly into the first socket and working properly on other games. I will add support for the Wiimote and Nunchuck at some point. Once it's complete enough for me to use version numbers, I'll start making binary releases. Sorry for the lack of commits. I've been out of town on vacation and couldn't work on this like I want. I should have lots of time next week.

**Comment by ghost** [comment]
lack of commits is not a problem - this is the nature of wii homebrew - there are 2 other similar projects on github.  I will try to compile it again and test when I get a chance.  my wii and dev environment is uptodate so that may be causing a compatibility issue.

**Comment by camthesaxman** [comment]
Devkitpro version shouldn't really matter as long as it's reasonably up to date. I'm using a version that I downloaded about 4 months ago. Just make sure the controller is in the Player 1 port. I'll look at this tomorrow when I finally get home from the trip and have access to my computer and Wii.

**Comment by ghost** [comment]
Ok, cool, cool, prob

**Comment by ghost** [comment]
Yes, found the problem.  it is working fine.  Apparently my black gamecube controller is dead.  :(

**Comment by camthesaxman** [comment]
I have made a release for version 0.0.1 and provided compiled binaries.
